# Generated by Django 5.2.6 on 2025-09-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('shampoo', 'Shampoo'), ('condicionador', 'Condicionador'), ('mascara', 'Máscara Capilar'), ('oleo', 'Óleo Capilar'), ('creme', 'Creme de Pentear'), ('gel', 'Gel'), ('mousse', 'Mousse'), ('spray', 'Spray'), ('coloracao', 'Coloração'), ('descolorante', 'Descolorante'), ('tools', 'Ferramentas'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('affiliate_link', models.URLField(verbose_name='Link de Afiliado')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
