# Generated by Django 5.2.6 on 2025-10-05 10:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('trial_10', 'Plano Explorador (10 dias)'), ('vip_30', 'Plano Revolucionário (30 dias)')], max_length=10, unique=True, verbose_name='Tipo de Plano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço (R$)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preço do Plano',
                'verbose_name_plural': 'Preços dos Planos',
                'ordering': ['plan_type'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('shampoo', 'Shampoo'), ('condicionador', 'Condicionador'), ('mascara', 'Máscara Capilar'), ('oleo', 'Óleo Capilar'), ('creme', 'Creme de Pentear'), ('gel', 'Gel'), ('mousse', 'Mousse'), ('spray', 'Spray'), ('coloracao', 'Coloração'), ('descolorante', 'Descolorante'), ('tools', 'Ferramentas'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('affiliate_link', models.URLField(verbose_name='Link de Afiliado')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de cashback que o comerciante receberá após a compra (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Cashback (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Compra')),
                ('cashback_percentage_at_purchase', models.DecimalField(decimal_places=2, help_text='Percentual de cashback no momento da compra', max_digits=5, verbose_name='% Cashback na Compra')),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Cashback')),
                ('click_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Clique no Link')),
                ('purchase_confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação da Compra')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('affiliate_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pedido no Sistema de Afiliados')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP do Usuário')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Página de Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='admin_panel.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rastreamento de Compra',
                'verbose_name_plural': 'Rastreamentos de Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Cashback Ganho'), ('paid', 'Cashback Pago'), ('cancelled', 'Cashback Cancelado')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_tracking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transaction', to='admin_panel.purchasetracking')),
            ],
            options={
                'verbose_name': 'Transação de Cashback',
                'verbose_name_plural': 'Transações de Cashback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCashbackBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Ganho')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Pago')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo Disponível')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Cashback',
                'verbose_name_plural': 'Saldos de Cashback',
            },
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['user', 'status'], name='admin_panel_user_id_9e0b83_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['product', 'status'], name='admin_panel_product_ac7d39_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_55ad77_idx'),
        ),
    ]
