# Generated by Django 5.2.6 on 2025-09-28 22:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_planpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de cashback que o comerciante receberá após a compra (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cashback (%)'),
        ),
    ]
