# Generated by Django 5.2.6 on 2025-09-28 22:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_add_cashback_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de cashback que o comerciante receberá após a compra (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Cashback (%)'),
        ),
    ]
