# Generated by Django 5.2.6 on 2025-09-29 08:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_fix_cashback_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Compra')),
                ('cashback_percentage_at_purchase', models.DecimalField(decimal_places=2, help_text='Percentual de cashback no momento da compra', max_digits=5, verbose_name='% Cashback na Compra')),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Cashback')),
                ('click_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Clique no Link')),
                ('purchase_confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação da Compra')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('affiliate_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pedido no Sistema de Afiliados')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP do Usuário')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Página de Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='admin_panel.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rastreamento de Compra',
                'verbose_name_plural': 'Rastreamentos de Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Cashback Ganho'), ('paid', 'Cashback Pago'), ('cancelled', 'Cashback Cancelado')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_tracking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transaction', to='admin_panel.purchasetracking')),
            ],
            options={
                'verbose_name': 'Transação de Cashback',
                'verbose_name_plural': 'Transações de Cashback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCashbackBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Ganho')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Pago')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo Disponível')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Cashback',
                'verbose_name_plural': 'Saldos de Cashback',
            },
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['user', 'status'], name='admin_panel_user_id_9e0b83_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['product', 'status'], name='admin_panel_product_ac7d39_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasetracking',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_55ad77_idx'),
        ),
    ]
