# Generated by Django 5.2.6 on 2025-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL do avatar/foto de perfil', max_length=500, null=True),
        ),
    ]
