# Generated by Django 5.2.6 on 2025-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('employee', 'Funcionário'), ('client', 'Cliente')], default='client', max_length=10),
        ),
    ]
