# Generated by Django 5.2.6 on 2025-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Foto de perfil', max_length=500, null=True),
        ),
    ]
