
# Generated by Django 5.2.6 on 2025-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_picture_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_pics/'),
        ),
    ]
