# Generated by Django 5.2.6 on 2025-10-05 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Multa')),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Aplicada (%)')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('hours_before_appointment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas antes do agendamento')),
                ('cancelled_at', models.DateTimeField(verbose_name='Data e Hora do Cancelamento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Multa Paga')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multa de Cancelamento',
                'verbose_name_plural': 'Multas de Cancelamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token único')),
                ('temp_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome temporário')),
                ('temp_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone temporário')),
                ('temp_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email temporário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link de Agendamento',
                'verbose_name_plural': 'Links de Agendamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Data do Agendamento')),
                ('appointment_time', models.TimeField(verbose_name='Horário do Agendamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('rescheduled', 'Reagendado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído'), ('no_show', 'Não compareceu')], default='pending', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('rescheduled_date', models.DateField(blank=True, null=True, verbose_name='Nova Data (Reagendamento)')),
                ('rescheduled_time', models.TimeField(blank=True, null=True, verbose_name='Novo Horário (Reagendamento)')),
                ('rescheduled_reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Reagendamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
