# Generated by Django 5.2.6 on 2025-10-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salons.employee', verbose_name='Funcionário responsável'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon', verbose_name='Salão'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.service', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='cancellationfee',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_fee', to='appointments.appointment', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='cancellationfee',
            name='cancelled_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.employee', verbose_name='Funcionário do Agendamento'),
        ),
        migrations.AddField(
            model_name='linkagendamento',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_link', to=settings.AUTH_USER_MODEL, verbose_name='Cliente vinculado'),
        ),
        migrations.AddField(
            model_name='linkagendamento',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='salons.salon', verbose_name='Salão'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['salon', 'appointment_date'], name='appointment_salon_i_f2c0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee', 'appointment_date'], name='appointment_employe_30264f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_c5b816_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('status__in', ['scheduled', 'confirmed'])), fields=('salon', 'employee', 'appointment_date', 'appointment_time'), name='unique_employee_appointment_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True), ('status__in', ['scheduled', 'confirmed'])), fields=('salon', 'appointment_date', 'appointment_time'), name='unique_salon_appointment_time_no_employee'),
        ),
    ]
