# Generated by Django 5.2.6 on 2025-09-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('salons', '0002_bookingtoken_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salons.employee', verbose_name='Funcionário responsável'),
        ),
    ]
