# Generated by Django 5.2.6 on 2025-09-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_employee'),
        ('salons', '0002_bookingtoken_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('salon', 'employee', 'appointment_date', 'appointment_time'), name='unique_employee_appointment_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True)), fields=('salon', 'appointment_date', 'appointment_time'), name='unique_salon_appointment_time_no_employee'),
        ),
    ]
