# Generated by Django 5.2.6 on 2025-09-23 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_unique_together_and_more'),
        ('salons', '0004_salon_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nova Data (Reagendamento)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Reagendamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Novo Horário (Reagendamento)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('rescheduled', 'Reagendado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído'), ('no_show', 'Não compareceu')], default='pending', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LinkAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token único')),
                ('temp_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome temporário')),
                ('temp_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone temporário')),
                ('temp_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email temporário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_link', to=settings.AUTH_USER_MODEL, verbose_name='Cliente vinculado')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='salons.salon', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Link de Agendamento',
                'verbose_name_plural': 'Links de Agendamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
