# Generated by Django 5.2.6 on 2025-09-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_appointment_salon_i_f2c0f8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Multa')),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Aplicada (%)')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('hours_before_appointment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas antes do agendamento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Multa Paga')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_fee', to='appointments.appointment', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Multa de Cancelamento',
                'verbose_name_plural': 'Multas de Cancelamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
