# Generated by Django 5.2.6 on 2025-09-29 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_cancellationfee'),
        ('salons', '0013_salon_cancellation_fee_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_employee_appointment_time',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_salon_appointment_time_no_employee',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('status__in', ['scheduled', 'confirmed'])), fields=('salon', 'employee', 'appointment_date', 'appointment_time'), name='unique_employee_appointment_time'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True), ('status__in', ['scheduled', 'confirmed'])), fields=('salon', 'appointment_date', 'appointment_time'), name='unique_salon_appointment_time_no_employee'),
        ),
    ]
