# Generated by Django 5.2.6 on 2025-09-22 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Salão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('monday_open', models.TimeField(blank=True, null=True, verbose_name='Segunda - Abertura')),
                ('monday_close', models.TimeField(blank=True, null=True, verbose_name='Segunda - Fechamento')),
                ('tuesday_open', models.TimeField(blank=True, null=True, verbose_name='Terça - Abertura')),
                ('tuesday_close', models.TimeField(blank=True, null=True, verbose_name='Terça - Fechamento')),
                ('wednesday_open', models.TimeField(blank=True, null=True, verbose_name='Quarta - Abertura')),
                ('wednesday_close', models.TimeField(blank=True, null=True, verbose_name='Quarta - Fechamento')),
                ('thursday_open', models.TimeField(blank=True, null=True, verbose_name='Quinta - Abertura')),
                ('thursday_close', models.TimeField(blank=True, null=True, verbose_name='Quinta - Fechamento')),
                ('friday_open', models.TimeField(blank=True, null=True, verbose_name='Sexta - Abertura')),
                ('friday_close', models.TimeField(blank=True, null=True, verbose_name='Sexta - Fechamento')),
                ('saturday_open', models.TimeField(blank=True, null=True, verbose_name='Sábado - Abertura')),
                ('saturday_close', models.TimeField(blank=True, null=True, verbose_name='Sábado - Fechamento')),
                ('sunday_open', models.TimeField(blank=True, null=True, verbose_name='Domingo - Abertura')),
                ('sunday_close', models.TimeField(blank=True, null=True, verbose_name='Domingo - Fechamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Salão',
                'verbose_name_plural': 'Salões',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('duration', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
    ]
