# Generated by Django 5.2.6 on 2025-09-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Token de agendamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_token', to='salons.salon', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Token de Agendamento',
                'verbose_name_plural': 'Tokens de Agendamento',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Data de contratação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='salons.salon', verbose_name='Salão')),
                ('services', models.ManyToManyField(blank=True, to='salons.service', verbose_name='Serviços que pode executar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
