# Generated by Django 5.2.6 on 2025-09-22 22:22

from django.db import migrations, models


def migrate_operating_hours(apps, schema_editor):
    """
    Migra dados dos campos individuais de segunda-sexta para o campo agrupado weekdays
    """
    Salon = apps.get_model('salons', 'Salon')
    
    for salon in Salon.objects.all():
        # Coleta horários de segunda a sexta
        weekday_hours = []
        for day in ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']:
            open_time = getattr(salon, f'{day}_open')
            close_time = getattr(salon, f'{day}_close')
            if open_time and close_time:
                weekday_hours.append((open_time, close_time))
        
        # Define política de conversão: usar o primeiro horário válido encontrado
        if weekday_hours:
            # Pegar o primeiro horário válido como padrão para semana
            first_open, first_close = weekday_hours[0]
            salon.weekdays_open = first_open
            salon.weekdays_close = first_close
            salon.save()
            
            # Log se houver horários diferentes para aviso
            all_same = all(
                (open_time, close_time) == (first_open, first_close) 
                for open_time, close_time in weekday_hours
            )
            if not all_same:
                print(f"AVISO: Salão '{salon.name}' tinha horários diferentes nos dias úteis. Usando horário de segunda-feira como padrão.")


def reverse_migrate_operating_hours(apps, schema_editor):
    """
    Reverte a migração copiando weekdays de volta para os campos individuais
    """
    Salon = apps.get_model('salons', 'Salon')
    
    for salon in Salon.objects.all():
        if salon.weekdays_open and salon.weekdays_close:
            # Copia horário da semana para todos os dias úteis
            for day in ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']:
                setattr(salon, f'{day}_open', salon.weekdays_open)
                setattr(salon, f'{day}_close', salon.weekdays_close)
            salon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_bookingtoken_employee'),
    ]

    operations = [
        # Passo 1: Adicionar novos campos
        migrations.AddField(
            model_name='salon',
            name='weekdays_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Segunda à Sexta - Fechamento'),
        ),
        migrations.AddField(
            model_name='salon',
            name='weekdays_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Segunda à Sexta - Abertura'),
        ),
        
        # Passo 2: Migrar dados existentes
        migrations.RunPython(
            migrate_operating_hours,
            reverse_migrate_operating_hours
        ),
        
        # Passo 3: Remover campos antigos
        migrations.RemoveField(
            model_name='salon',
            name='friday_close',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='monday_close',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='thursday_close',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='tuesday_close',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='wednesday_close',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='wednesday_open',
        ),
    ]