# Generated by Django 5.2.6 on 2025-09-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_safe_operating_hours_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='salon_photos/', verbose_name='Foto do Salão'),
        ),
    ]
