# Generated by Django 5.2.6 on 2025-09-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salon_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingToken',
        ),
    ]
