# Generated by Django 5.2.6 on 2025-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_remove_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Foto do Salão'),
        ),
    ]
