# Generated by Django 5.2.6 on 2025-09-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_alter_salon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='photo',
        ),
    ]
