# Generated by Django 5.2.6 on 2025-09-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_remove_salon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Foto do Salão'),
        ),
    ]
