# Generated by Django 5.2.6 on 2025-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_salon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='salon_photos/', verbose_name='Foto do Salão'),
        ),
    ]
