# Generated by Django 5.2.6 on 2025-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_alter_salon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='closed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechado até'),
        ),
        migrations.AddField(
            model_name='salon',
            name='closure_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo do Fechamento'),
        ),
        migrations.AddField(
            model_name='salon',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False, verbose_name='Temporariamente Fechado'),
        ),
    ]
