# Generated by Django 5.2.6 on 2025-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_salon_closed_until_salon_closure_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Foto do Salão'),
        ),
    ]
