# Generated by Django 5.2.6 on 2025-09-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_appointment_salon_i_f2c0f8_idx_and_more'),
        ('salons', '0011_alter_salon_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Porcentagem sobre cada serviço realizado (apenas se tipo for 'Porcentagem por Serviço')", max_digits=5, verbose_name='Porcentagem de Comissão (%)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('weekly', 'Semanal'), ('daily', 'Diário'), ('percentage', 'Porcentagem por Serviço')], default='monthly', max_length=10, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mensal, semanal ou diário conforme tipo escolhido', max_digits=10, verbose_name='Valor do Salário'),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=7, verbose_name='Tipo de Transação')),
                ('category', models.CharField(max_length=20, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('reference_month', models.PositiveIntegerField(verbose_name='Mês de Referência (1-12)')),
                ('reference_year', models.PositiveIntegerField(verbose_name='Ano de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment', verbose_name='Agendamento Relacionado')),
                ('related_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.employee', verbose_name='Funcionário Relacionado')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='salons.salon', verbose_name='Salão')),
            ],
            options={
                'verbose_name': 'Registro Financeiro',
                'verbose_name_plural': 'Registros Financeiros',
                'ordering': ['-reference_year', '-reference_month', '-created_at'],
                'indexes': [models.Index(fields=['salon', 'reference_year', 'reference_month'], name='salons_fina_salon_i_1c2f9e_idx'), models.Index(fields=['transaction_type', 'category'], name='salons_fina_transac_fe660c_idx')],
            },
        ),
    ]
