# Generated by Django 5.2.6 on 2025-09-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_employee_commission_percentage_employee_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='cancellation_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentagem do valor do serviço cobrada como multa', max_digits=5, verbose_name='Multa de Cancelamento (%)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cancellation_hours_threshold',
            field=models.PositiveIntegerField(default=12, help_text='Cancelamentos com menos tempo que isso serão multados', verbose_name='Prazo para Cancelamento sem Multa (horas)'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cancellation_policy_enabled',
            field=models.BooleanField(default=False, verbose_name='Política de Cancelamento Habilitada'),
        ),
    ]
